@extends('layouts.master')

@section('title', 'Refind Policy')

@section('content')
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:.0001pt;'><strong><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>Skiez Travels And Logistics&nbsp;</span></strong><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;background:white;'>has no role whatsoever if the airline decides to cancel the flight. The flight can be cancelled owing to bad weather, bankruptcy, and natural disaster. However,&nbsp;</span><strong><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>Skiez Travels And Logistics</span></strong><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;background:white;'>&nbsp;will inform the passengers regarding flight cancellation at the earliest.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:.0001pt;'>&nbsp;</p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin-top:0in;margin-bottom:15.0pt;line-height:18.0pt;'><strong><span style='font-family:"Arial","sans-serif";color:#333333;'>Billing</span></strong><span style='font-family:"Arial","sans-serif";color:#333333;'>: Your credit card may be billed in multiple charges but it should not exceed the total amount. All transaction service fees are 100% non-refundable.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin-top:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-family:"Arial","sans-serif";color:#333333;'>Service Fees &ndash; No representations are made for the service fees charged. It is only for site usage and booking creation. No representations are made for service fees charged for booking through our call center and those fees may be higher. There are no representations or warranties except for using our call center agent&rsquo;s assistance in searching various airfares and other travel products and making the booking. All types of service fees may change at any time and the most updated fees may not be reflected here.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;margin-top:0in;line-height:18.0pt;'><strong><span style='font-family:"Arial","sans-serif";color:#333333;'>Changes to flights already purchased</span></strong></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin-top:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-family:"Arial","sans-serif";color:#333333;'>Any and all changes made to the itinerary are subject to airline fare rules and restricted, whichever is more restrictive; most of our tickets, hotels, packages, and cruises do not allow any date or name changes after the booking is made.&nbsp;<strong><span style='font-family:"Arial","sans-serif";'>Skiez Travels And Logistics Private Limited</span></strong><strong>&nbsp;</strong>does not guarantee, and shall not be responsible for, any bookings or reservations made or confirmed to you in the event that the original itinerary has been changed by the supplier pursuant to the customer&rsquo;s request or supplier&rsquo;s schedule changes</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin-top:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-family:"Arial","sans-serif";color:#333333;'>&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><strong><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>Cancel and Exchange&nbsp;</span></strong></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>Most of our airline tickets are <strong>100% non-refundable*</strong>. In certain cases where the airline may allow cancellations, a credit may be valid towards a future ticket purchase by the same traveller with travel on the same airline. An applicable penalty and a fare difference (if any), will be added in these cases. Usually, the credit issued by the airline supplier is valid with time constraints and specific expiration date and should be discussed with a customer service agent. All such bookings where the cancellation may be permitted must be cancelled prior to the scheduled departure time of the first flight segment by calling our customer service centre.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>We do not guarantee any cancellation. A cancellation fee, as specified by the agent must be paid to us at the time of cancelling the booking; we retain this fee. The credit will be held for a limited time period, please ask the customer service agent for the specific date by when you must use this credit or you will lose the credit amount. When you are ready to make the new booking, you will have to pay the fare difference (if any), applicable airline penalties for that fare</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>All such changes are governed by the airlines&rsquo; rules and regulations and are not under our control. <strong>Skiez Travels And Logistics</strong> not provide any guarantees on changes or fees. If you are cancelling the booking and applying for a refund,&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><strong><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>Multiple Airline Itineraries</span></strong><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>If your Itinerary consists of more than one airline, then two separate fare rules will be used, different rules and policies (for example, for baggage fees, change fees, and refunds) may apply in each direction or for each airline. For changes, refunds, exchanges, each airline may charge separately. In case of Schedule change or cancellations: if your initial flight is cancelled or the schedule is changed by either you or the airline, then the other airline with which you booked your return flight is not liable to issue a refund or change your itinerary.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>You are responsible for complying with each airline&rsquo;s terms and conditions, which may differ (for example, check-in times and limits on baggage size/weight). It is advisable to print your outbound and return portions of your e-ticket confirmation for all flights prior to travelling. You may be asked for proof of your return ticket at check-in.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><strong><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>Cancellation and Refunds&nbsp;</span></strong></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>Most of our airline tickets, hotels, pre-paid car rentals, vacation packages, and service fees are non-refundable. All cancellations are to be done only over the phone. Refund requests can be accepted only if the following conditions are met:</span></p>
<ul style="margin-bottom:0in;" type="disc">
    <li style='margin:0in;margin-bottom:     15.0pt;font-size:15px;font-family:"Calibri","sans-serif";color:#333333;line-height:13.5pt;'><span style='font-size:12px;font-family:"Arial","sans-serif";'>You have applied for a cancellation and refund with us and if the fare rules include cancellation and refunds.</span></li>
    <li style='margin:0in;margin-bottom:     15.0pt;font-size:15px;font-family:"Calibri","sans-serif";color:#333333;line-height:13.5pt;'><span style='font-size:12px;font-family:"Arial","sans-serif";'>You are not a &ldquo;no show&rdquo; (most &ldquo;no show&rdquo; bookings are in-eligible for any waiver from suppliers for refund processing).</span></li>
    <li style='margin:0in;margin-bottom:     15.0pt;font-size:15px;font-family:"Calibri","sans-serif";color:#333333;line-height:13.5pt;'><span style='font-size:12px;font-family:"Arial","sans-serif";'>We are able to procure waivers from suppliers to further process this requested cancellation and refund.</span></li>
</ul>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-size:16px;font-family:"Arial","sans-serif";color:#333333;'>We cannot provide a specific timeline as to how long it may take to process this requested refund. All refund requests are processed in a sequential format. Once you have made a cancellation request to our customer service agent, we will then send you an email notification regarding the received request. This notification does not automatically qualify you for a refund but it only provides you with an acknowledgement of your request and provides you with a tracking number. Upon receipt of your request, we will work with the suppliers such as airlines, hotels, and car-rental companies to generate a waiver based on airline and other supplier rules and notify you of the supplier decision. Our service fees associated with the original travel reservation or booking are not refundable. Please note that we are dependent on the suppliers for receiving the requested refunds.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:.0001pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin-top:0in;margin-bottom:15.0pt;line-height:18.0pt;'><span style='font-family:"Arial","sans-serif";color:#333333;'>&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Calibri","sans-serif";margin:0in;margin-bottom:.0001pt;'>&nbsp;</p>
@endsection